
# This file was generated by the Tkinter Designer by Parth Jadhav

# https://github.com/ParthJadhav/Tkinter-Designer



from pathlib import Path


# from tkinter import *

# Explicit imports to satisfy Flake8

from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import customtkinter



OUTPUT_PATH = Path(__file__).parent

ASSETS_PATH = OUTPUT_PATH / Path(r"/home/arrowdot/Documents/Monitor_App/assets/frame0")



def relative_to_assets(path: str) -> Path:

    return ASSETS_PATH / Path(path)



def on_sign_in():
    
    window.destroy()
    import gui1
    gui1.window




window = Tk()


window.geometry("1024x720")

window.configure(bg = "#FFFFFF")


entry_font = customtkinter.CTkFont(family="Arial", size=16)



canvas = Canvas(

    window,

    bg = "#FFFFFF",

    height = 720,

    width = 1024,

    bd = 0,

    highlightthickness = 0,

    relief = "ridge"

)


canvas.place(x = 0, y = 0)

canvas.create_text(

    484.5166015625,

    91.0,

    anchor="nw",

    text="Robot Cafe",

    fill="#11284C",

    font=("CADTMonoDisplay Regular", 40 * -1)

)


image_image_1 = PhotoImage(

    file=relative_to_assets("image_1.png"))

image_1 = canvas.create_image(

    427.0,

    90.0,

    image=image_image_1

)




username_entry = customtkinter.CTkEntry(

    window, 

    placeholder_text="Username", 

    placeholder_text_color='#11284c',

    font=entry_font, 

    border_color='#11284c',

    corner_radius=0,  

    height=64,

    width=440

)  



username_entry.place(

    x=293.0,

    y=262.0,

)
# image_image_2 = PhotoImage(
#     file=relative_to_assets("image_2.png"))
# image_2 = canvas.create_image(
#     768.0,
#     395.0,
#     image=image_image_2
# )

# icon_button = customtkinter.CTkButton(master= window, image=image_image_2, text="", command=(print('click'))) 


password_entry = customtkinter.CTkEntry(

    window, 

    placeholder_text="Password", 

    font=entry_font,

    placeholder_text_color='#11284c', 

    border_color='#11284c',

    corner_radius=0,  

    height=64,

    width=440

)



password_entry.place(

    x=293.0,

    y=360.77496337890625,

)




button_image_1 = PhotoImage(

    file=relative_to_assets("button_1.png"))

button_submit = Button(

    image=button_image_1,

    borderwidth=0,

    highlightthickness=0,

    command=on_sign_in,

    relief="flat"

)

button_submit.place(

    x=293.0,

    y=485.15826416015625,

    width=439.0,

    height=65.8499984741211

)



window.resizable(False, False)

window.mainloop() 





