
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import customtkinter

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/arrowdot/Documents/Monitor_App/assets/frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x720")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    64.0,
    117.0,
    anchor="nw",
    text="Choose your drink",
    fill="#11284C",
    font=("Niradei Bold", 32 * -1)
)

# scroll_frame = customtkinter.CTkScrollbar(master=window, )
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=44.0,
    y=211.0,
    width=185.10841369628906,
    height=235.8418426513672
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=294.0,
    y=211.0,
    width=185.10841369628906,
    height=235.8418426513672
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=544.0,
    y=211.0,
    width=185.10841369628906,
    height=235.8418426513672
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=794.0,
    y=211.0,
    width=185.10841369628906,
    height=235.8418426513672
)

canvas.create_rectangle(
    0.0,
    0.0,
    1024.0,
    102.0,
    fill="#FFFFFF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    108.0,
    49.0,
    image=image_image_1
)

canvas.create_text(
    164.3662109375,
    37.4525146484375,
    anchor="nw",
    text="Robot Cafe",
    fill="#11284C",
    font=("CADTMonoDisplay Regular", 32 * -1)
)
window.resizable(False, False)
window.mainloop()
