
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x720")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    496.0,
    0.0,
    1024.0,
    570.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    496.0,
    0.0,
    1024.0,
    284.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    496.0,
    0.0,
    1024.0,
    284.0,
    fill="#11284C",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=338.0,
    y=610.0,
    width=316.0545654296875,
    height=66.37145233154297
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    243.0,
    338.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    244.0,
    357.0,
    image=image_image_2
)

canvas.create_text(
    536.0,
    475.0,
    anchor="nw",
    text="Total $2.00",
    fill="#FF4438",
    font=("Niradei Bold", 48 * -1)
)

canvas.create_text(
    536.0,
    311.0,
    anchor="nw",
    text="Payment Method",
    fill="#000000",
    font=("Niradei Bold", 24 * -1)
)

canvas.create_text(
    576.0,
    360.0,
    anchor="nw",
    text="Cash",
    fill="#000000",
    font=("Niradei Regular", 24 * -1)
)

canvas.create_rectangle(
    536.0,
    366.0,
    560.0,
    390.0,
    fill="#000000",
    outline="")

canvas.create_text(
    576.0,
    415.0,
    anchor="nw",
    text="ABA Scan",
    fill="#000000",
    font=("Niradei Regular", 24 * -1)
)

canvas.create_rectangle(
    536.0,
    421.0,
    560.0,
    445.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0618896484375,
    1024.0,
    128.0,
    fill="#FF4438",
    outline="")

canvas.create_text(
    262.0,
    35.0,
    anchor="nw",
    text="Current order",
    fill="#FFFFFF",
    font=("CADTMonoDisplay Regular", 48 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=86.0,
    y=50.0,
    width=45.0,
    height=47.0
)

canvas.create_text(
    544.0,
    168.0,
    anchor="nw",
    text="Green Tea",
    fill="#FFFFFF",
    font=("Niradei Bold", 28 * -1)
)

canvas.create_text(
    544.0,
    209.0,
    anchor="nw",
    text="2.00$",
    fill="#FFFFFF",
    font=("Niradei Regular", 24 * -1)
)

canvas.create_text(
    945.0,
    178.0,
    anchor="nw",
    text="x1",
    fill="#FFFFFF",
    font=("Niradei Bold", 28 * -1)
)
window.resizable(False, False)
window.mainloop()
